server:
  port: 8001

mybatis:
  #config-location: classpath:mybatis/SqlMapConfig.xml        # mybatis配置文件所在路径
  type-aliases-package: com.itheima.hf.cloud.pojo    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mapper/*.xml                       # mapper映射文件

eureka:
   client:
     service-url:
       defaultZone: http://eureka01:7001/eureka,http://eureka02:7002/eureka,http://eureka03:7003/eureka   #  链接Eureka Server地址  集群版
#       defaultZone: http://localhost:7001/eureka   # 链接Eureka Server地址
   instance:
     instance-id: hf-itheima-cloud-provider:8001		#修改别名
     prefer-ip-address: true							#显示IP地址

spring:
   application:
    name: hf-itheima-cloud-provider      # 重要  唯一建议使用项目名称， 不要有“下划线”
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=utf-8
    # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间


info:
  app.name: hf-itheima-cloud-provider
  company.name: www.itheima.com
  build.artifactId: hf_itheima_cloud
  build.version: 1.0